product:
    headers:
        name: ConstantContact # name, comment here to force newline in template
        version: 5.9.0 # version, comment here to force newline in template
    files:
        'install.constantcontact.php':
            composephp:
                - platform/plg_jomlink/src/install.jomlink.php
        'constantcontact.php':
            composephp:
                - platform/plg_jomlink/src/jomlink.php
                - modules/constantcontact/constantcontact.php
        'constantcontact.xml':
            buildpluginxml:
                module: modules/constantcontact/constantcontact.yml
                platform: platform/plg_jomlink/platform.yml
                template: platform/plg_jomlink/src/jomlink.xml
        'manifest.xml':
            buildpluginxml:
                module: modules/constantcontact/constantcontact.yml
                platform: platform/plg_jomlink/platform.yml
                template: platform/plg_jomlink/src/manifest.xml
