<?php

class iContact {

  var $url =  'https://app.sandbox.icontact.com/icp';
  var $appid;
  var $username;
  var $password;

  var $acctid = '';
  var $clientfolderid = '';

  function __construct($appid, $username, $password) {
    $this->appid = $appid;
    $this->username = $username;
    $this->password = $password;    
  }


  function trace($msg) {
    //    print_r($msg);
  }

  function callResource($resource, $method = 'GET', $data = null) {
    $accountid = $this->getAccountId();
    $clientfolderid  = $this->getClientFolderId();
    $url = "/a/$accountid/c/$clientfolderid/$resource/";

    if (is_array($data)) {
      print_r($data);
//      $data = json_encode($data);
      $data = json_encode(array($resource => $data));
      print_r(json_decode($data,true));
    }

    return $this->_callResource($url, $method, $data);    
  }

  function _callResource($url, $method = 'GET', $data = null)
  {
    $url    = $this->url . $url;

    $headers = array(
    'Accept: application/json',
    'Content-Type: application/json',
    'Api-Version: 2.2',
    'Api-AppId: ' . $this->appid,
    'Api-Username: ' . $this->username,
    'Api-Password: ' . $this->password,
    );

    $handle = curl_init();
    curl_setopt($handle, CURLOPT_URL, $url);
    curl_setopt($handle, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($handle, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($handle, CURLOPT_SSL_VERIFYHOST, false);

    switch ($method) {
      case 'POST':
        curl_setopt($handle, CURLOPT_POST, true);
        curl_setopt($handle, CURLOPT_POSTFIELDS, json_encode($data));
        break;
      case 'PUT':
        curl_setopt($handle, CURLOPT_PUT, true);
        $file_handle = fopen($data, 'r');
        curl_setopt($handle, CURLOPT_INFILE, $file_handle);
        break;
      case 'DELETE':
        curl_setopt($handle, CURLOPT_CUSTOMREQUEST, 'DELETE');
        break;
    }

    $response = curl_exec($handle);    
    $response = json_decode($response, true);
    $this->trace($response);
    $code = curl_getinfo($handle, CURLINFO_HTTP_CODE);
    curl_close($handle);

    if ($code != 200) {
      throw new Exception("Could not connect:\n" . print_r($response, true), $code);
    }

    return $response;
  }

  function dump($array)
  {
    echo "<pre>" . print_r($array, true) . "</pre>";
  }


  function getAccountId($acctid = '') {    
    // We already have it, do nothing
    if ($acctid) $this->acctid= $acctid;

    if (!$acctid) {
      $data = $this->_callResource('/a/');
      $this->acctid = $data['accounts'][0]['accountId'];      
    }     

    return $this->acctid;
  }

  function getClientFolderId($folderid = '') {
    if ($clientfolderid) $this->folderid = $folderid;

    if (!$this->clientfolderid) {
      $accountid = $this->getAccountId();
      $data = $this->_callResource("/a/{$accountid}/c/");
      $this->clientfolderid = $data['clientfolders'][0]['clientFolderId'];
    }
    return $this->clientfolderid;    
  }
}


$icontact = new iContact('giV3qEHF0QSvMPIzZ3yxFNmKKYt44sEb', 'mwg-gizmo', 'passw0rd2');
$ic = &$icontact;
# $acctid = $icontact->getAccountId();
# print $icontact->getClientFolderId();
// print_r( $icontact->callResource('lists'));
//print_r($icontact->callResource('lists/186267'));
// nt_r($icontact->callResource('lists/186267'));

$data = // array('lists' =>
          array(
            array(
            'name' =>  'MWG - pending', 
            'emailOwnerOnChange' => 0,
            'welcomeOnManualAdd' => 0,
            'welcomeOnSignupAdd' => 0,
            'welcomeMessageId'   => 825286,
            'description'        => 'MWG Autogenerated List for site'
          ),
          array(
            'name' =>  'MWG - confirmed', 
            'emailOwnerOnChange' => 0,
            'welcomeOnManualAdd' => 0,
            'welcomeOnSignupAdd' => 0,
            'welcomeMessageId'   => 825286,
            'description'        => 'MWG Autogenerated List for site'
          ),

          
       );
// );

# print_r($ic->callResource('messages'));
print_r($ic->callResource('contacts'));
//
print_r($icontact->callResource('lists', 'POST', $data));
// print_r( $icontact->callResource('lists'));

//print_r($icontact);
print_r($ic);

