product:
    headers:
        name: iContact # name, comment here to force newline in template
        version: 1.0.0 # version, comment here to force newline in template
    files:
        'icontact.php':
            params2json:
                params: modules/icontact/icontact.yml
            composephp:
                - platform/newsletter_plugin/src/plugin.php
                - platform/newsletter_plugin/src/settings.php
                - platform/newsletter_plugin/src/platform.php
                - platform/newsletter_plugin/src/updater.php
                - modules/icontact/icontact.php

