product:
    headers:
        name: GetResponse # name, comment here to force newline in template
        version: 5.9.0 # version, comment here to force newline in template
    files:
        'install.getresponse.php':
            composephp:
                - platform/plg_jomlink/src/install.jomlink.php
        'getresponse.php':
            composephp:
                - platform/plg_jomlink/src/jomlink.php
                - modules/getresponse/getresponse.php
        'getresponse.xml':
            buildpluginxml:
                module: modules/getresponse/getresponse.yml
                platform: platform/plg_jomlink/platform.yml
                template: platform/plg_jomlink/src/jomlink.xml
        'manifest.xml':
            buildpluginxml:
                module: modules/getresponse/getresponse.yml
                platform: platform/plg_jomlink/platform.yml
                template: platform/plg_jomlink/src/manifest.xml
