product:
    headers:
        name: MailChimp # name, comment here to force newline in template
        version: 1.0.0 # version, comment here to force newline in template
    files:
        'mailchimp.php':
            params2json:
                params: modules/mailchimp/mailchimp.yml
            composephp:
                - platform/newsletter_plugin/src/plugin.php
                - platform/newsletter_plugin/src/settings.php
                - platform/newsletter_plugin/src/platform.php
                - platform/newsletter_plugin/src/updater.php
                - modules/mailchimp/mailchimp.php

