product:
    headers:
        name: ConstantContact # name, comment here to force newline in template
        version: 1.0.0 # version, comment here to force newline in template
    files:
        'constantcontact.php':
            params2json:
                params: modules/constantcontact/constantcontact.yml
            composephp:
                - platform/newsletter_plugin/src/plugin.php
                - platform/newsletter_plugin/src/settings.php
                - platform/newsletter_plugin/src/platform.php
                - platform/newsletter_plugin/src/updater.php
                - modules/constantcontact/constantcontact.php

